---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  tags:
    - apt
    - pkg

- name: remove default package
  ansible.builtin.apt:
    name: 
    - vim
    - tiny-vim
    state: absent
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  tags:
    - apt
    - pkg

- name: Required apt-get system packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  tags:
    - apt
    - pkg
  

- name: Required apt-get system packages
  ansible.builtin.apt:
    name: "{{ apt_programming_packages }}"
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  tags:
    - apt
    - pkg
    - development

- name: remove default package
  ansible.builtin.dnf:
    name: 
    - vim
    - tiny-vim
    state: absent
    autoremove: true
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  tags:
    - apt
    - pkg

- name: Upgrade yum packages
  ansible.builtin.command: dnf update -y
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  tags:
    - dnf
    - pkg

- name: Required dnf system packages
  ansible.builtin.dnf:
    name: "{{ dnf_packages }}"
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  tags:
    - dnf
    - pkg

- name: Development dnf packages
  ansible.builtin.dnf:
    name: "{{ dnf_programming_packages }}"
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  tags:
    - dnf
    - pkg
    - development

- name: Include task list in play
  ansible.builtin.include_tasks:
    file: dotfiles.yml

...
